[versions]
spring-boot = "4.0.0"
spring-ai = "2.0.0-M3"
postgresql = "42.7.4"
ojdbc = "23.6.0.24.10"
testcontainers = "1.20.4"
commons-lang3 = "3.14.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-ai-mcp-server = { module = "org.springframework.ai:spring-ai-starter-mcp-server", version.ref = "spring-ai" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
ojdbc11 = { module = "com.oracle.database.jdbc:ojdbc11", version.ref = "ojdbc" }
orai18n = { module = "com.oracle.database.nls:orai18n", version.ref = "ojdbc" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-oracle-free = { module = "org.testcontainers:oracle-free", version.ref = "testcontainers" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
