package ru.it_spectrum.ai.jdbc.mcp.sql;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.ParenthesedStatement;
import net.sf.jsqlparser.statement.ExplainStatement;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.Statements;
import net.sf.jsqlparser.statement.delete.ParenthesedDelete;
import net.sf.jsqlparser.statement.insert.ParenthesedInsert;
import net.sf.jsqlparser.statement.select.ParenthesedSelect;
import net.sf.jsqlparser.statement.select.PlainSelect;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.statement.select.SetOperationList;
import net.sf.jsqlparser.statement.select.WithItem;
import net.sf.jsqlparser.statement.update.ParenthesedUpdate;
import org.springframework.stereotype.Component;
import ru.it_spectrum.ai.jdbc.mcp.config.JdbcProperties;

import java.util.Set;

/**
 * Lightweight syntactic SQL guard. Intended to protect the database from accidental
 * write operations generated by an LLM (e.g. {@code "let me try on a clean table, DELETE first"}).
 *
 * <p>This is <b>not</b> a replacement for proper database-level permissions. Its purpose is to
 * reject anything that is obviously not a pure read, <i>before</i> it reaches the JDBC driver.
 *
 * <p>Algorithm:
 * <ol>
 *     <li>Try to parse the statement with JSqlParser and inspect the AST;</li>
 *     <li>If parsing fails (for example because of dialect-specific syntax), fall back to the
 *         original lightweight lexical guard;</li>
 *     <li>The lexical fallback strips line ({@code --}) and block ({@code /* *}{@code /})
 *         comments, rejects multi-statement input, requires the first token to be one of
 *         {@code SELECT}, {@code WITH}, or {@code EXPLAIN}, and scans the whole statement for
 *         DML/DDL keywords outside of string literals and
 *         quoted identifiers — this catches bypass patterns such as
 *         {@code WITH x AS (INSERT ... RETURNING *) SELECT * FROM x},
 *         {@code SELECT ... INTO new_table FROM ...}, and {@code SELECT ... FOR UPDATE}.</li>
 * </ol>
 *
 * <p>Can be disabled via {@code jdbc.readonly-guard=off} if the user explicitly opts out.
 */
@Component
public class ReadOnlyGuard {

    private static final Set<String> ALLOWED_FIRST_TOKENS = Set.of("SELECT", "WITH", "EXPLAIN");

    /**
     * Tokens that must not appear in a read-only statement. Matched case-insensitively as whole
     * identifiers (word-boundary), skipping content inside {@code '...'} literals and
     * {@code "..."} quoted identifiers.
     */
    private static final Set<String> FORBIDDEN_KEYWORDS = Set.of(
            "INSERT", "UPDATE", "DELETE", "MERGE", "UPSERT", "TRUNCATE",
            "CREATE", "DROP", "ALTER", "RENAME",
            "GRANT", "REVOKE",
            "CALL", "EXEC", "EXECUTE",
            "COMMIT", "ROLLBACK", "SAVEPOINT", "LOCK",
            "INTO", "COPY"
    );

    private final boolean enabled;

    public ReadOnlyGuard(JdbcProperties properties) {
        this.enabled = properties.guardEnabled();
    }

    /**
     * @throws SqlNotAllowedException if the statement is not a pure read operation
     */
    public void check(String sql) {
        if (!enabled) {
            return;
        }
        if (sql == null || sql.isBlank()) {
            throw new SqlNotAllowedException("SQL is empty");
        }
        Statements statements;
        try {
            statements = parseStatementsForGuard(sql);
        } catch (JSQLParserException | RuntimeException e) {
            checkLexically(sql);
            return;
        }
        checkParsedStatements(statements);
    }

    private Statements parseStatementsForGuard(String sql) throws JSQLParserException {
        String stripped = stripComments(sql).trim();
        while (stripped.endsWith(";")) {
            stripped = stripped.substring(0, stripped.length() - 1).trim();
        }
        if (stripped.isEmpty()) {
            throw new SqlNotAllowedException("SQL contains only comments");
        }
        String firstToken = firstToken(stripped).toUpperCase();
        if (!ALLOWED_FIRST_TOKENS.contains(firstToken)) {
            throw new SqlNotAllowedException(
                    "Only SELECT / WITH / EXPLAIN statements are allowed in read-only mode. " +
                            "Got: '" + firstToken + "'. " +
                            "(Set jdbc.readonly-guard=off to disable this client-side check.)");
        }

        return CCJSqlParserUtil.parseStatements(stripped);
    }

    private void checkParsedStatements(Statements statements) {
        if (statements.size() != 1) {
            throw new SqlNotAllowedException(
                    "Multiple SQL statements are not allowed — send a single SELECT/WITH/EXPLAIN");
        }
        Statement statement = statements.getFirst();
        if (statement instanceof ExplainStatement explain) {
            if (explain.getStatement() == null) {
                throw new SqlNotAllowedException("Read-only guard: EXPLAIN must wrap a SELECT/WITH statement");
            }
            checkSelect(explain.getStatement());
            return;
        }
        if (statement instanceof Select select) {
            checkSelect(select);
            return;
        }
        throw new SqlNotAllowedException(
                "Only SELECT / WITH / EXPLAIN statements are allowed in read-only mode. " +
                        "Got: '" + statement.getClass().getSimpleName() + "'. " +
                        "(Set jdbc.readonly-guard=off to disable this client-side check.)");
    }

    private void checkSelect(Select select) {
        if (select.getForClause() != null || select.getForMode() != null
                || select.getForUpdateTable() != null || select.getWait() != null
                || select.isNoWait() || select.isSkipLocked()) {
            throw new SqlNotAllowedException(
                    "Read-only guard: FOR UPDATE / locking clauses are not allowed in read-only mode. " +
                            "(Set jdbc.readonly-guard=off to disable this client-side check.)");
        }
        if (select.getWithItemsList() != null) {
            for (WithItem<?> item : select.getWithItemsList()) {
                checkWithItem(item);
            }
        }
        switch (select) {
            case PlainSelect plain -> {
                if ((plain.getIntoTables() != null && !plain.getIntoTables().isEmpty())
                        || plain.getIntoTempTable() != null) {
                    throw new SqlNotAllowedException(
                            "Read-only guard: SELECT INTO is not allowed in read-only mode. " +
                                    "(Set jdbc.readonly-guard=off to disable this client-side check.)");
                }
                return;
            }
            case ParenthesedSelect parenthesed -> {
                if (parenthesed.getSelect() != null) {
                    checkSelect(parenthesed.getSelect());
                }
                return;
            }
            case SetOperationList set -> {
                if (set.getSelects() != null) {
                    for (Select nested : set.getSelects()) {
                        checkSelect(nested);
                    }
                }
                return;
            }
            default -> {
            }
        }
        throw new SqlNotAllowedException(
                "Read-only guard: unsupported SELECT form '" + select.getClass().getSimpleName() + "'. " +
                        "Use a SELECT / WITH / EXPLAIN query or disable the client-side guard explicitly.");
    }

    private void checkWithItem(WithItem<?> item) {
        ParenthesedStatement body = item.getParenthesedStatement();
        if (body instanceof ParenthesedInsert) {
            throw forbiddenCte("INSERT");
        }
        if (body instanceof ParenthesedUpdate) {
            throw forbiddenCte("UPDATE");
        }
        if (body instanceof ParenthesedDelete) {
            throw forbiddenCte("DELETE");
        }
        if (body instanceof ParenthesedSelect select && select.getSelect() != null) {
            checkSelect(select.getSelect());
        }
    }

    private SqlNotAllowedException forbiddenCte(String keyword) {
        return new SqlNotAllowedException(
                "Read-only guard: forbidden " + keyword + " statement inside CTE. " +
                        "(Set jdbc.readonly-guard=off to disable this client-side check.)");
    }

    private void checkLexically(String sql) {
        String stripped = stripComments(sql).trim();
        while (stripped.endsWith(";")) {
            stripped = stripped.substring(0, stripped.length() - 1).trim();
        }
        if (stripped.isEmpty()) {
            throw new SqlNotAllowedException("SQL contains only comments");
        }
        if (containsStatementSeparator(stripped)) {
            throw new SqlNotAllowedException(
                    "Multiple SQL statements are not allowed — send a single SELECT/WITH/EXPLAIN");
        }
        String firstToken = firstToken(stripped).toUpperCase();
        if (!ALLOWED_FIRST_TOKENS.contains(firstToken)) {
            throw new SqlNotAllowedException(
                    "Only SELECT / WITH / EXPLAIN statements are allowed in read-only mode. " +
                            "Got: '" + firstToken + "'. " +
                            "(Set jdbc.readonly-guard=off to disable this client-side check.)");
        }
        String forbidden = findForbiddenKeyword(stripped);
        if (forbidden != null) {
            throw new SqlNotAllowedException(
                    "Read-only guard: forbidden keyword '" + forbidden + "' in statement body. " +
                            "This typically indicates a DML hidden in a CTE " +
                            "(e.g. WITH x AS (INSERT ...) SELECT ...), a SELECT INTO, " +
                            "or a FOR UPDATE locking clause. " +
                            "(Set jdbc.readonly-guard=off to disable this client-side check.)");
        }
    }

    /** Removes line ({@code --...}) and block ({@code /* ... *}{@code /}) comments. */
    static String stripComments(String sql) {
        StringBuilder out = new StringBuilder(sql.length());
        int i = 0;
        int len = sql.length();
        boolean inSingle = false;
        boolean inDouble = false;
        while (i < len) {
            char c = sql.charAt(i);
            if (inSingle) {
                out.append(c);
                if (c == '\'' && i + 1 < len && sql.charAt(i + 1) == '\'') {
                    out.append(sql.charAt(i + 1));
                    i += 2;
                    continue;
                }
                if (c == '\'') {
                    inSingle = false;
                }
                i++;
            } else if (inDouble) {
                out.append(c);
                if (c == '"' && i + 1 < len && sql.charAt(i + 1) == '"') {
                    out.append(sql.charAt(i + 1));
                    i += 2;
                    continue;
                }
                if (c == '"') inDouble = false;
                i++;
            } else if (c == '\'' ) {
                inSingle = true;
                out.append(c);
                i++;
            } else if (c == '"') {
                inDouble = true;
                out.append(c);
                i++;
            } else if (c == '-' && i + 1 < len && sql.charAt(i + 1) == '-') {
                // Line comment — skip to end of line.
                while (i < len && sql.charAt(i) != '\n') i++;
            } else if (c == '/' && i + 1 < len && sql.charAt(i + 1) == '*') {
                // Block comment — skip to terminating */.
                i += 2;
                while (i + 1 < len && !(sql.charAt(i) == '*' && sql.charAt(i + 1) == '/')) i++;
                i = Math.min(i + 2, len);
            } else {
                out.append(c);
                i++;
            }
        }
        return out.toString();
    }

    static boolean containsStatementSeparator(String sql) {
        boolean inSingle = false;
        boolean inDouble = false;
        for (int i = 0; i < sql.length(); i++) {
            char c = sql.charAt(i);
            if (inSingle) {
                if (c == '\'' && i + 1 < sql.length() && sql.charAt(i + 1) == '\'') {
                    i++;
                } else if (c == '\'') {
                    inSingle = false;
                }
            } else if (inDouble) {
                if (c == '"' && i + 1 < sql.length() && sql.charAt(i + 1) == '"') {
                    i++;
                } else if (c == '"') {
                    inDouble = false;
                }
            } else if (c == '\'') {
                inSingle = true;
            } else if (c == '"') {
                inDouble = true;
            } else if (c == ';') {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns the first {@link #FORBIDDEN_KEYWORDS} token found outside string literals
     * and quoted identifiers, or {@code null} if none is present. Matching is word-bounded:
     * {@code DROP} in {@code some_drop_view} is not a match, but a bare {@code DROP} is.
     * Comments are stripped first so callers do not get false positives from commented-out SQL.
     */
    static String findForbiddenKeyword(String sql) {
        sql = stripComments(sql);
        boolean inSingle = false;
        boolean inDouble = false;
        int len = sql.length();
        int tokenStart = -1;
        for (int i = 0; i <= len; i++) {
            char c = i < len ? sql.charAt(i) : '\0';
            if (inSingle) {
                if (c == '\'' && i + 1 < len && sql.charAt(i + 1) == '\'') {
                    i++;
                } else if (c == '\'') {
                    inSingle = false;
                }
                continue;
            }
            if (inDouble) {
                if (c == '"' && i + 1 < len && sql.charAt(i + 1) == '"') {
                    i++;
                } else if (c == '"') {
                    inDouble = false;
                }
                continue;
            }
            if (c == '\'') {
                // End any token we were building before entering the string literal.
                if (tokenStart >= 0) {
                    String tok = sql.substring(tokenStart, i).toUpperCase();
                    if (FORBIDDEN_KEYWORDS.contains(tok)) return tok;
                    tokenStart = -1;
                }
                inSingle = true;
                continue;
            }
            if (c == '"') {
                if (tokenStart >= 0) {
                    String tok = sql.substring(tokenStart, i).toUpperCase();
                    if (FORBIDDEN_KEYWORDS.contains(tok)) return tok;
                    tokenStart = -1;
                }
                inDouble = true;
                continue;
            }
            boolean isIdentChar = Character.isLetter(c) || c == '_'
                    || (tokenStart >= 0 && Character.isDigit(c));
            if (isIdentChar) {
                if (tokenStart < 0) tokenStart = i;
            } else if (tokenStart >= 0) {
                String tok = sql.substring(tokenStart, i).toUpperCase();
                if (FORBIDDEN_KEYWORDS.contains(tok)) return tok;
                tokenStart = -1;
            }
        }
        return null;
    }

    static String firstToken(String sql) {
        int i = 0;
        int len = sql.length();
        while (i < len && Character.isWhitespace(sql.charAt(i))) i++;
        int start = i;
        while (i < len && (Character.isLetter(sql.charAt(i)) || sql.charAt(i) == '_')) i++;
        return sql.substring(start, i);
    }
}
