package ru.it_spectrum.ai.jdbc.mcp.sql;

import org.springframework.stereotype.Component;
import ru.it_spectrum.ai.jdbc.mcp.config.JdbcProperties;

import java.util.Set;

/**
 * Lightweight "first-keyword" SQL guard. Intended to protect the database from accidental
 * write operations generated by an LLM (e.g. {@code "let me try on a clean table, DELETE first"}).
 *
 * <p>This is <b>not</b> a replacement for proper database-level permissions. Its purpose is to
 * reject anything that is obviously not a pure read, <i>before</i> it reaches the JDBC driver.
 *
 * <p>Algorithm:
 * <ol>
 *     <li>Strip line ({@code --}) and block ({@code /* *}{@code /}) comments;</li>
 *     <li>Reject input that contains more than one statement (semicolons inside the body);</li>
 *     <li>Require the first non-whitespace token to be one of {@code SELECT}, {@code WITH},
 *         or {@code EXPLAIN}.</li>
 * </ol>
 *
 * <p>Can be disabled via {@code jdbc.readonly-guard=off} if the user explicitly opts out.
 */
@Component
public class ReadOnlyGuard {

    private static final Set<String> ALLOWED_FIRST_TOKENS = Set.of("SELECT", "WITH", "EXPLAIN");

    private final boolean enabled;

    public ReadOnlyGuard(JdbcProperties properties) {
        this.enabled = properties.guardEnabled();
    }

    /**
     * @throws SqlNotAllowedException if the statement is not a pure read operation
     */
    public void check(String sql) {
        if (!enabled) {
            return;
        }
        if (sql == null || sql.isBlank()) {
            throw new SqlNotAllowedException("SQL is empty");
        }
        String stripped = stripComments(sql).trim();
        while (stripped.endsWith(";")) {
            stripped = stripped.substring(0, stripped.length() - 1).trim();
        }
        if (stripped.isEmpty()) {
            throw new SqlNotAllowedException("SQL contains only comments");
        }
        if (containsStatementSeparator(stripped)) {
            throw new SqlNotAllowedException(
                    "Multiple SQL statements are not allowed — send a single SELECT/WITH/EXPLAIN");
        }
        String firstToken = firstToken(stripped).toUpperCase();
        if (!ALLOWED_FIRST_TOKENS.contains(firstToken)) {
            throw new SqlNotAllowedException(
                    "Only SELECT / WITH / EXPLAIN statements are allowed in read-only mode. " +
                            "Got: '" + firstToken + "'. " +
                            "(Set jdbc.readonly-guard=off to disable this client-side check.)");
        }
    }

    /** Removes line ({@code --...}) and block ({@code /* ... *}{@code /}) comments. */
    static String stripComments(String sql) {
        StringBuilder out = new StringBuilder(sql.length());
        int i = 0;
        int len = sql.length();
        boolean inSingle = false;
        boolean inDouble = false;
        while (i < len) {
            char c = sql.charAt(i);
            if (inSingle) {
                out.append(c);
                if (c == '\'' && (i + 1 >= len || sql.charAt(i + 1) != '\'')) {
                    inSingle = false;
                }
                i++;
            } else if (inDouble) {
                out.append(c);
                if (c == '"') inDouble = false;
                i++;
            } else if (c == '\'' ) {
                inSingle = true;
                out.append(c);
                i++;
            } else if (c == '"') {
                inDouble = true;
                out.append(c);
                i++;
            } else if (c == '-' && i + 1 < len && sql.charAt(i + 1) == '-') {
                // Line comment — skip to end of line.
                while (i < len && sql.charAt(i) != '\n') i++;
            } else if (c == '/' && i + 1 < len && sql.charAt(i + 1) == '*') {
                // Block comment — skip to terminating */.
                i += 2;
                while (i + 1 < len && !(sql.charAt(i) == '*' && sql.charAt(i + 1) == '/')) i++;
                i = Math.min(i + 2, len);
            } else {
                out.append(c);
                i++;
            }
        }
        return out.toString();
    }

    static boolean containsStatementSeparator(String sql) {
        boolean inSingle = false;
        boolean inDouble = false;
        for (int i = 0; i < sql.length(); i++) {
            char c = sql.charAt(i);
            if (inSingle) {
                if (c == '\'' && (i + 1 >= sql.length() || sql.charAt(i + 1) != '\'')) inSingle = false;
            } else if (inDouble) {
                if (c == '"') inDouble = false;
            } else if (c == '\'') {
                inSingle = true;
            } else if (c == '"') {
                inDouble = true;
            } else if (c == ';') {
                return true;
            }
        }
        return false;
    }

    static String firstToken(String sql) {
        int i = 0;
        int len = sql.length();
        while (i < len && Character.isWhitespace(sql.charAt(i))) i++;
        int start = i;
        while (i < len && (Character.isLetter(sql.charAt(i)) || sql.charAt(i) == '_')) i++;
        return sql.substring(start, i);
    }
}
