package ru.it_spectrum.ai.jdbc.mcp.integration;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import ru.it_spectrum.ai.jdbc.mcp.config.JdbcProperties;
import ru.it_spectrum.ai.jdbc.mcp.dialect.OracleDialect;
import ru.it_spectrum.ai.jdbc.mcp.dialect.SqlDialect;
import ru.it_spectrum.ai.jdbc.mcp.metadata.MetadataService;
import ru.it_spectrum.ai.jdbc.mcp.sql.QueryResult;
import ru.it_spectrum.ai.jdbc.mcp.sql.ReadOnlyGuard;
import ru.it_spectrum.ai.jdbc.mcp.sql.SqlExecutor;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * End-to-end check against Oracle Free via Testcontainers.
 * Run with: {@code ./gradlew integrationTest}
 *
 * <p>The Oracle Free image is large (~1.5 GB) and the first boot takes minutes.
 */
@Tag("integration")
@Testcontainers
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class OracleIntegrationTest {

    @Container
    static final OracleContainer ORACLE = new OracleContainer("gvenzl/oracle-free:23-slim-faststart")
            .withUsername("jdbcmcp")
            .withPassword("jdbcmcp");

    private SqlExecutor executor;
    private MetadataService metadata;
    private String schema;

    @BeforeAll
    void setup() throws Exception {
        ORACLE.start();
        schema = ORACLE.getUsername().toUpperCase();
        try (Connection c = oraAdmin()) {
            try (var st = c.createStatement()) {
                st.execute("CREATE TABLE customers (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(200) NOT NULL, email VARCHAR2(200) UNIQUE)");
                st.execute("CREATE INDEX idx_customers_name ON customers(name)");
                st.execute("CREATE TABLE orders (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id NUMBER REFERENCES customers(id), total NUMBER(10,2))");
                st.execute("INSERT INTO customers(name, email) VALUES ('Alice', 'a@example.com')");
                st.execute("INSERT INTO customers(name, email) VALUES ('Bob', 'b@example.com')");
                st.execute("INSERT INTO orders(customer_id, total) VALUES (1, 10.5)");
                st.execute("INSERT INTO orders(customer_id, total) VALUES (1, 20.0)");
                st.execute("INSERT INTO orders(customer_id, total) VALUES (2, 5.0)");
                st.execute("COMMIT");
                st.execute("CREATE OR REPLACE VIEW v_customer_totals AS SELECT c.id, c.name, NVL(SUM(o.total), 0) AS total FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id, c.name");
            }
        }

        JdbcProperties props = new JdbcProperties(
                ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword(),
                schema, 30, 1000, 100, "strict");
        DataSource ds = buildPool(props);
        SqlDialect dialect = new OracleDialect();
        ReadOnlyGuard guard = new ReadOnlyGuard(props);
        executor = new SqlExecutor(ds, dialect, props, guard);
        metadata = new MetadataService(executor, dialect, props);
    }

    private Connection oraAdmin() throws SQLException {
        return java.sql.DriverManager.getConnection(ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword());
    }

    private DataSource buildPool(JdbcProperties p) {
        com.zaxxer.hikari.HikariConfig cfg = new com.zaxxer.hikari.HikariConfig();
        cfg.setJdbcUrl(p.url());
        cfg.setUsername(p.username());
        cfg.setPassword(p.password());
        cfg.setReadOnly(true);
        cfg.setMaximumPoolSize(2);
        return new com.zaxxer.hikari.HikariDataSource(cfg);
    }

    @Test
    void executeSimpleSelect() throws Exception {
        QueryResult r = executor.query("SELECT name, email FROM customers ORDER BY id", null, null, null);
        assertThat(r.rows()).hasSize(2);
        assertThat(r.rows().get(0).get("NAME")).isEqualTo("Alice");
    }

    @Test
    void executeParameterisedSelect() throws Exception {
        QueryResult r = executor.query("SELECT COUNT(*) AS c FROM orders WHERE customer_id = ?",
                List.of(1), null, null);
        assertThat(r.rows()).hasSize(1);
    }

    @Test
    void rejectsWriteViaGuard() {
        assertThatThrownBy(() -> executor.query("DELETE FROM customers", null, null, null))
                .hasMessageContaining("Only SELECT");
    }

    @Test
    void rejectsDmlAtTransactionLevel() throws Exception {
        // With SET TRANSACTION READ ONLY applied by OracleDialect, INSERT must be refused even
        // if we bypass the guard.
        JdbcProperties propsNoGuard = new JdbcProperties(
                ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword(),
                schema, 30, 1000, 100, "off");
        DataSource ds = buildPool(propsNoGuard);
        try (Connection c = ds.getConnection()) {
            new OracleDialect().prepareReadOnly(c);
            try (var st = c.createStatement()) {
                assertThatThrownBy(() -> st.execute("INSERT INTO customers(name, email) VALUES ('X', 'x@x')"))
                        .hasMessageContaining("ORA-");
            }
        }
    }

    @Test
    void describeTableReturnsFullShape() throws Exception {
        Map<String, Object> info = metadata.describeTable(schema, "ORDERS");
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> cols = (List<Map<String, Object>>) info.get("columns");
        assertThat(cols).extracting("name").contains("ID", "CUSTOMER_ID", "TOTAL");
        @SuppressWarnings("unchecked")
        Map<String, Object> pk = (Map<String, Object>) info.get("primaryKey");
        assertThat(pk).isNotNull();
    }

    @Test
    void viewDefinitionIsReturned() throws Exception {
        String def = metadata.viewDefinition(schema, "V_CUSTOMER_TOTALS");
        assertThat(def).containsIgnoringCase("FROM CUSTOMERS");
    }

    @Test
    void searchObjectsFindsViewAndTable() throws Exception {
        QueryResult r = metadata.searchObjects("CUSTOMER");
        assertThat(r.rows()).extracting(m -> m.get("NAME"))
                .contains("CUSTOMERS", "V_CUSTOMER_TOTALS");
    }
}
