package ru.it_spectrum.ai.jdbc.mcp.integration;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.testcontainers.oracle.OracleContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import ru.it_spectrum.ai.jdbc.mcp.config.JdbcProperties;
import ru.it_spectrum.ai.jdbc.mcp.dialect.OracleDialect;
import ru.it_spectrum.ai.jdbc.mcp.dialect.SqlDialect;
import ru.it_spectrum.ai.jdbc.mcp.metadata.DistributionService;
import ru.it_spectrum.ai.jdbc.mcp.metadata.MetadataService;
import ru.it_spectrum.ai.jdbc.mcp.metadata.StatsService;
import ru.it_spectrum.ai.jdbc.mcp.plan.OraclePlanParser;
import ru.it_spectrum.ai.jdbc.mcp.sql.QueryResult;
import ru.it_spectrum.ai.jdbc.mcp.sql.ReadOnlyGuard;
import ru.it_spectrum.ai.jdbc.mcp.sql.SqlExecutor;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * End-to-end check against Oracle Free via Testcontainers.
 * Run with: {@code ./gradlew integrationTest}
 *
 * <p>The Oracle Free image is large (~1.5 GB) and the first boot takes minutes.
 */
@Tag("integration")
@Testcontainers
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class OracleIntegrationTest {

    @Container
    static final OracleContainer ORACLE = new OracleContainer("gvenzl/oracle-free:23-slim-faststart")
            .withUsername("jdbcmcp")
            .withPassword("jdbcmcp");

    private SqlExecutor executor;
    private MetadataService metadata;
    private StatsService stats;
    private DistributionService distribution;
    private SqlDialect dialect;
    private String schema;

    @BeforeAll
    void setup() throws Exception {
        ORACLE.start();
        schema = ORACLE.getUsername().toUpperCase();
        try (Connection c = oraAdmin()) {
            try (var st = c.createStatement()) {
                st.execute("CREATE TABLE customers (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(200) NOT NULL, email VARCHAR2(200) UNIQUE)");
                st.execute("CREATE INDEX idx_customers_name ON customers(name)");
                st.execute("CREATE TABLE orders (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id NUMBER REFERENCES customers(id), total NUMBER(10,2))");
                st.execute("INSERT INTO customers(name, email) VALUES ('Alice', 'a@example.com')");
                st.execute("INSERT INTO customers(name, email) VALUES ('Bob', 'b@example.com')");
                st.execute("INSERT INTO orders(customer_id, total) VALUES (1, 10.5)");
                st.execute("INSERT INTO orders(customer_id, total) VALUES (1, 20.0)");
                st.execute("INSERT INTO orders(customer_id, total) VALUES (2, 5.0)");
                st.execute("COMMIT");
                st.execute("CREATE OR REPLACE VIEW v_customer_totals AS SELECT c.id, c.name, NVL(SUM(o.total), 0) AS total FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id, c.name");
            }
        }

        JdbcProperties props = new JdbcProperties(
                ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword(),
                schema, 30, 1000, 100, "strict");
        DataSource ds = buildPool(props);
        dialect = new OracleDialect();
        ReadOnlyGuard guard = new ReadOnlyGuard(props);
        executor = new SqlExecutor(ds, dialect, props, guard);
        metadata = new MetadataService(executor, dialect, props);
        stats    = new StatsService(executor, dialect, props);
        distribution = new DistributionService(executor, dialect, props, new OraclePlanParser());

        // Seed a skewed events table for distribution / null-ratio tests.
        try (Connection c = oraAdmin(); var st = c.createStatement()) {
            st.execute("CREATE TABLE events ("
                    + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "status VARCHAR2(20) NOT NULL, "
                    + "category VARCHAR2(20), "
                    + "amount NUMBER(10,2))");
            // 90 OK rows with category, 10 FAIL rows without.
            st.execute("INSERT INTO events(status, category, amount) "
                    + "SELECT 'OK', CASE WHEN MOD(LEVEL, 2) = 0 THEN 'A' ELSE 'B' END, LEVEL * 1.5 "
                    + "FROM dual CONNECT BY LEVEL <= 90");
            st.execute("INSERT INTO events(status, category, amount) "
                    + "SELECT 'FAIL', NULL, LEVEL * 0.1 "
                    + "FROM dual CONNECT BY LEVEL <= 10");
            st.execute("COMMIT");
        }

        // Gather Oracle optimiser stats for the seeded tables so tableStats / indexStats
        // return meaningful NUM_ROWS / DISTINCT_KEYS values.
        try (Connection c = oraAdmin(); var st = c.createStatement()) {
            st.execute("BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, 'CUSTOMERS'); END;");
            st.execute("BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, 'ORDERS'); END;");
            st.execute("BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, 'EVENTS'); END;");
        }
    }

    private Connection oraAdmin() throws SQLException {
        return java.sql.DriverManager.getConnection(ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword());
    }

    private DataSource buildPool(JdbcProperties p) {
        com.zaxxer.hikari.HikariConfig cfg = new com.zaxxer.hikari.HikariConfig();
        cfg.setJdbcUrl(p.url());
        cfg.setUsername(p.username());
        cfg.setPassword(p.password());
        cfg.setReadOnly(true);
        cfg.setMaximumPoolSize(2);
        return new com.zaxxer.hikari.HikariDataSource(cfg);
    }

    @Test
    void executeSimpleSelect() throws Exception {
        QueryResult r = executor.query("SELECT name, email FROM customers ORDER BY id", null, null, null);
        assertThat(r.rows()).hasSize(2);
        assertThat(r.rows().get(0).get("NAME")).isEqualTo("Alice");
    }

    @Test
    void executeParameterisedSelect() throws Exception {
        QueryResult r = executor.query("SELECT COUNT(*) AS c FROM orders WHERE customer_id = ?",
                List.of(1), null, null);
        assertThat(r.rows()).hasSize(1);
    }

    @Test
    void executeNamedParameterSelect() throws Exception {
        QueryResult r = executor.queryNamed(
                "SELECT COUNT(*) AS c FROM orders WHERE customer_id = :customerId",
                Map.of("customerId", 1), null, null);
        assertThat(r.rows()).hasSize(1);
    }

    @Test
    void rejectsWriteViaGuard() {
        assertThatThrownBy(() -> executor.query("DELETE FROM customers", null, null, null))
                .hasMessageContaining("Only SELECT");
    }

    @Test
    void rejectsDmlAtTransactionLevel() throws Exception {
        // With SET TRANSACTION READ ONLY applied by OracleDialect, INSERT must be refused even
        // if we bypass the guard.
        JdbcProperties propsNoGuard = new JdbcProperties(
                ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword(),
                schema, 30, 1000, 100, "off");
        DataSource ds = buildPool(propsNoGuard);
        try (Connection c = ds.getConnection()) {
            c.setAutoCommit(false);
            new OracleDialect().prepareReadOnly(c);
            try (var st = c.createStatement()) {
                assertThatThrownBy(() -> st.execute("INSERT INTO customers(name, email) VALUES ('X', 'x@x')"))
                        .hasMessageContaining("ORA-");
            } finally {
                c.rollback();
                c.setAutoCommit(true);
            }
        }
    }

    @Test
    void describeTableReturnsFullShape() throws Exception {
        Map<String, Object> info = metadata.describeTable(schema, "ORDERS");
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> cols = (List<Map<String, Object>>) info.get("columns");
        assertThat(cols).extracting("name").contains("ID", "CUSTOMER_ID", "TOTAL");
        @SuppressWarnings("unchecked")
        Map<String, Object> pk = (Map<String, Object>) info.get("primaryKey");
        assertThat(pk).isNotNull();
    }

    @Test
    void viewDefinitionIsReturned() throws Exception {
        String def = metadata.viewDefinition(schema, "V_CUSTOMER_TOTALS");
        assertThat(def).containsIgnoringCase("FROM CUSTOMERS");
    }

    @Test
    void searchObjectsFindsViewAndTable() throws Exception {
        QueryResult r = metadata.searchObjects("CUSTOMER");
        assertThat(r.rows()).extracting(m -> m.get("NAME"))
                .contains("CUSTOMERS", "V_CUSTOMER_TOTALS");
    }

    @Test
    void tableStatsReturnsRowCount() throws Exception {
        Map<String, Object> s = stats.tableStats(schema, "CUSTOMERS");
        assertThat(s.get("found")).isEqualTo(Boolean.TRUE);
        // ALL_TABLES aliases table_name → uppercase column label on Oracle.
        Object rows = s.get("ESTIMATED_ROWS");
        if (rows == null) rows = s.get("estimated_rows");
        assertThat(((Number) rows).longValue()).isGreaterThanOrEqualTo(2L);
    }

    @Test
    void indexStatsExposesPkAndSecondary() throws Exception {
        QueryResult r = stats.indexStats(schema, "CUSTOMERS");
        // Oracle reports column labels in upper case.
        String nameKey = r.columns().contains("INDEX_NAME") ? "INDEX_NAME" : "index_name";
        assertThat(r.rows()).extracting(m -> m.get(nameKey))
                .contains("IDX_CUSTOMERS_NAME");
        // is_primary 'Y' on exactly one row (the PK-backing index).
        String pkKey = r.columns().contains("IS_PRIMARY") ? "IS_PRIMARY" : "is_primary";
        assertThat(r.rows()).anyMatch(m -> "Y".equals(m.get(pkKey)));
    }

    @Test
    void fkIndexCoverageFlagsUnindexedFk() throws Exception {
        @SuppressWarnings("unchecked")
        Map<String, Object> r = stats.fkIndexCoverage(schema, "ORDERS");
        assertThat(((Number) r.get("uncovered_count")).intValue()).isGreaterThanOrEqualTo(1);
    }

    @Test
    void columnDistributionExposesSkew() throws Exception {
        Map<String, Object> r = distribution.columnDistribution(schema, "EVENTS", "STATUS", 5);
        assertThat(((Number) r.get("total_rows")).longValue()).isEqualTo(100L);
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> values = (List<Map<String, Object>>) r.get("values");
        assertThat(values).hasSize(2);
        assertThat(values.get(0).get("value")).isEqualTo("OK");
        assertThat(((Number) values.get(0).get("frequency")).longValue()).isEqualTo(90L);
    }

    @Test
    void columnHistogramReportsPercentiles() throws Exception {
        Map<String, Object> r = distribution.columnHistogram(schema, "EVENTS", "AMOUNT");
        assertThat(((Number) r.get("total_rows")).longValue()).isEqualTo(100L);
        assertThat(r.get("percentile_function")).isEqualTo("percentile_cont");
        double min = ((Number) r.get("min")).doubleValue();
        double max = ((Number) r.get("max")).doubleValue();
        double p50 = ((Number) r.get("p50")).doubleValue();
        assertThat(p50).isBetween(min, max);
    }

    @Test
    void nullRatioFlagsCategoryColumn() throws Exception {
        Map<String, Object> r = distribution.nullRatio(schema, "EVENTS");
        assertThat(((Number) r.get("total_rows")).longValue()).isEqualTo(100L);
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> cols = (List<Map<String, Object>>) r.get("columns");
        Map<String, Object> category = cols.stream()
                .filter(c -> "CATEGORY".equals(c.get("column")))
                .findFirst().orElseThrow();
        assertThat(((Number) category.get("null_rows")).longValue()).isEqualTo(10L);
    }

    @Test
    void estimateSelectivityUsesExplainPlan() throws Exception {
        Map<String, Object> r = distribution.estimateSelectivity(schema, "EVENTS", "status = 'FAIL'");
        // Oracle's static EXPLAIN returns an estimate even without ANALYZE; just ensure the
        // shape is present and the estimate is smaller than (or equal to) the baseline.
        Long estimated = ((Number) r.get("estimated_rows")).longValue();
        Long baseline  = ((Number) r.get("baseline_rows")).longValue();
        assertThat(estimated).isNotNull();
        assertThat(baseline).isNotNull();
        assertThat(estimated).isLessThanOrEqualTo(baseline);
    }

    @Test
    void joinCardinalityEstimatesInnerJoin() throws Exception {
        Map<String, Object> r = distribution.joinCardinality(
                schema, "CUSTOMERS", "ID",
                schema, "ORDERS", "CUSTOMER_ID", "INNER");
        assertThat(r.get("join_type")).isEqualTo("INNER");
        Long estimated = ((Number) r.get("estimated_rows")).longValue();
        assertThat(estimated).isNotNull();
        assertThat(estimated).isGreaterThan(0L);
    }

    @Test
    void unusedIndexesReportsNotSupportedOnOracle() throws Exception {
        Map<String, Object> r = stats.unusedIndexes(schema, null);
        assertThat(r.get("supported")).isEqualTo(Boolean.FALSE);
        assertThat((String) r.get("note")).contains("DBA_INDEX_USAGE");
    }
}
